// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvjnHpanXulF8BcGbsna0zlcwQBs713zg',
    appId: '1:34564543295:web:5d1c877abedac4096e798a',
    messagingSenderId: '34564543295',
    projectId: 'salonapp-3ba4c',
    authDomain: 'salonapp-3ba4c.firebaseapp.com',
    storageBucket: 'salonapp-3ba4c.firebasestorage.app',
    measurementId: 'G-Q5MBPFR902',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnV1do04truNyGQF9UzwAx9oDAuAq_Pdc',
    appId: '1:34564543295:android:6e74f1a9177fc3856e798a',
    messagingSenderId: '34564543295',
    projectId: 'salonapp-3ba4c',
    storageBucket: 'salonapp-3ba4c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUaCpfN56GHzqCP3DRAH6Q-WC_IaxNx2k',
    appId: '1:34564543295:ios:e25b1e0ef0198b506e798a',
    messagingSenderId: '34564543295',
    projectId: 'salonapp-3ba4c',
    storageBucket: 'salonapp-3ba4c.firebasestorage.app',
    iosBundleId: 'com.example.salonApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUaCpfN56GHzqCP3DRAH6Q-WC_IaxNx2k',
    appId: '1:34564543295:ios:e25b1e0ef0198b506e798a',
    messagingSenderId: '34564543295',
    projectId: 'salonapp-3ba4c',
    storageBucket: 'salonapp-3ba4c.firebasestorage.app',
    iosBundleId: 'com.example.salonApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvjnHpanXulF8BcGbsna0zlcwQBs713zg',
    appId: '1:34564543295:web:79688e2eb5f6340a6e798a',
    messagingSenderId: '34564543295',
    projectId: 'salonapp-3ba4c',
    authDomain: 'salonapp-3ba4c.firebaseapp.com',
    storageBucket: 'salonapp-3ba4c.firebasestorage.app',
    measurementId: 'G-NBY61Z1E9Y',
  );
}
